SELECT * FROM MEMBER;

--탈퇴해서 로그인 안됬을때 다시 돌리기
--update member set state = 0 where id = 'admin';
DROP TABLE GALLCOMMENT;
CREATE TABLE GALLCOMMENT
(
	CNO NUMBER PRIMARY KEY,
	ID VARCHAR2(64) NOT NULL UNIQUE,
	CONTENT VARCHAR2(4000),
	POSTDATE DATE,
	IP VARCHAR2(100)
);
DROP TABLE GALLERYBOARD;
CREATE TABLE GALLERYBOARD
(
	GNO NUMBER PRIMARY KEY,
	ID VARCHAR2(64) NOT NULL UNIQUE,
	TITLE VARCHAR2(2000),
	CONTENT VARCHAR2(4000),
	POSTDATE DATE,
	LASTMODIDATE DATE,
	IP VARCHAR2(100),
	LOOKCOUNT NUMBER,
	FILENAME VARCHAR2(500)
);

DROP TABLE FREEBOARD;
CREATE TABLE FREEBOARD
(
	FNO NUMBER PRIMARY KEY,
	ID VARCHAR2(64),
	CONTENT VARCHAR2(4000),
	POSTDATE DATE,
	IP VARCHAR2(100),
	STATE NUMBER,
	GROUPNO NUMBER,
	GROUPORD NUMBER,
	DEPTH NUMBER
);

DROP TABLE MEMBER;
CREATE TABLE MEMBER
(
	MNO NUMBER PRIMARY KEY,
	ID VARCHAR2(64) NOT NULL UNIQUE,
	PW VARCHAR2(64) NOT NULL,
	NAME VARCHAR2(64) NOT NULL,
	PHONE VARCHAR2(13), 
	EMAIL VARCHAR2(100) NOT NULL UNIQUE,
	ADDRESS VARCHAR2(100),
	REGDATE DATE,
	STATE NUMBER
);

ALTER TABLE GALLERYBOARD ADD CONSTRAINT gallaryboard_member_fk FOREIGN KEY(id) REFERENCES MEMBER(ID);
ALTER TABLE GALLCOMMENT ADD CONSTRAINT gallcomment_gallaryBoard_fk FOREIGN KEY(id) REFERENCES GALLERYBOARD(ID);
ALTER TABLE FREEBOARD ADD CONSTRAINT freeBoard_member_fk FOREIGN KEY(id) REFERENCES MEMBER(ID);

DROP SEQUENCE MEMBER_SEQ;
DROP SEQUENCE GALLERYBOARD_SEQ;
DROP SEQUENCE GALLCOMMENT_SEQ;
DROP SEQUENCE FREEBOARD_SEQ;

CREATE SEQUENCE MEMBER_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;
CREATE SEQUENCE GALLERYBOARD_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;
CREATE SEQUENCE GALLCOMMENT_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;
CREATE SEQUENCE FREEBOARD_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;

INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'admin', '~A11', '관리자', '010-1234-5678', 'soeun1365@naver.com', '서울시', SYSDATE, 0);
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'user1', '~A11', '사용자', '010-9876-5432', 'soeun1365@daum.net', '서울시', SYSDATE, 1); --탈퇴회원
