DROP TABLE MEMBER;
CREATE TABLE MEMBER
(
	M_NO NUMBER PRIMARY KEY,
	ID VARCHAR2(64),
	PW VARCHAR2(64),
	NAME VARCHAR2(64),
	PHONE VARCHAR2(13),	--010-1234-5678 (슬래시 포함13자)
	EMAIL VARCHAR2(100),
	ADDRESS VARCHAR2(100),
	REGDATE DATE,
	M_STATE NUMBER
);

DROP TABLE GALLERYBOARD;
CREATE TABLE GALLERYBOARD
(
	G_NO NUMBER PRIMARY KEY,
	ID VARCHAR2(64),
	TITLE VARCHAR2(2000),
	CONTENT VARCHAR2(4000),
	POSTDATE DATE,
	LASTMODIDATE DATE,
	IP VARCHAR2(100),
	LOOKCOUNT NUMBER,
	IMAGE VARCHAR2(500)
);

DROP TABLE GALLCOMMENT;
CREATE TABLE GALLCOMMENT
(
	C_NO NUMBER PRIMARY KEY,
	ID VARCHAR2(100),
	CONTENT VARCHAR2(4000),
	POSTDATE DATE,
	IP VARCHAR2(100)
);

DROP TABLE FREEBOARD;
CREATE TABLE FREEBOARD
(
	F_NO NUMBER PRIMARY KEY,
	ID VARCHAR2(64),
	CONTENT VARCHAR2(4000),
	POSTDATE DATE,
	IP VARCHAR2(100),
	STATE NUMBER,
	GROUPNO NUMBER,
	GROUPORD NUMBER,
	DEPTH NUMBER
);


DROP SEQUENCE MEMBER_SEQ;
DROP SEQUENCE GALLERYBOARD_SEQ;
DROP SEQUENCE GALLCOMMENT_SEQ;
DROP SEQUENCE FREEBOARD_SEQ;

CREATE SEQUENCE MEMBER_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;
CREATE SEQUENCE GALLERYBOARD_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;
CREATE SEQUENCE GALLCOMMENT_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;
CREATE SEQUENCE FREEBOARD_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;

INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'admin', '1111', '관리자', '010-1234-5678', 'admin@home.com', '서울시', SYSDATE, 0);